import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./features/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  safelist: [
    "lg:col-span-4",
    "lg:col-span-6",
    "lg:col-span-8",
    "lg:col-span-12",
  ],
  theme: {
    extend: {
      colors: {
        background: "#101419",
        surface: "#101419",
        "surface-dim": "#101419",
        "surface-bright": "#36393f",
        "surface-container-lowest": "#0a0e13",
        "surface-container-low": "#181c21",
        "surface-container": "#1c2025",
        "surface-container-high": "#262a30",
        "surface-container-highest": "#31353b",
        "on-surface": "#e0e2ea",
        "on-surface-variant": "#bfc7d2",
        "inverse-surface": "#e0e2ea",
        "inverse-on-surface": "#2d3136",
        outline: "#89929b",
        "outline-variant": "#3f4850",
        "surface-tint": "#93ccff",
        primary: {
          DEFAULT: "#93ccff",
          bright: "#0284c7",
          container: "#3198dc",
          "on-container": "#002c47",
        },
        "on-primary": "#003351",
        secondary: {
          DEFAULT: "#ffb690",
          bright: "#f97316",
          container: "#ec6a06",
          "on-container": "#4a1c00",
        },
        "on-secondary": "#552100",
        tertiary: {
          DEFAULT: "#b9c8de",
          bright: "#94a3b8",
          container: "#8392a6",
          "on-container": "#1c2b3c",
        },
        "on-tertiary": "#233143",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
      },
      fontFamily: {
        headline: ["var(--font-space-grotesk)", "Space Grotesk", "sans-serif"],
        body: ["var(--font-hanken-grotesk)", "Hanken Grotesk", "sans-serif"],
        label: ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-hero": ["56px", { lineHeight: "64px", fontWeight: "700" }],
        "headline-hero-mobile": ["36px", { lineHeight: "44px", fontWeight: "700" }],
        "headline-lg": ["38px", { lineHeight: "46px", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "headline-md": ["26px", { lineHeight: "34px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "label-sm": ["10px", { lineHeight: "14px", fontWeight: "500" }],
      },
      spacing: {
        gutter: "1.5rem",
        "gutter-sm": "1rem",
        "gutter-lg": "2rem",
        margin: "2rem",
        "margin-sm": "1rem",
        "margin-lg": "4rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
